spring.application.name=taskflow-b

# DB — с указанием значений по умолчанию
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:asersaai}
spring.datasource.password=${DB_PASSWORD:1212}

# system
spring.jpa.hibernate.ddl-auto=validate
# pool-max
spring.datasource.hikari.maximum-pool-size=8

# jwt key
jwt.secret=SGVsbG8hIFRoaXMgaXMgYSBsb25nIEJhc2U2NCBlbmNvZGVkIHN0cmluZyBjcmVhdGVkIGZvciB0ZXN0aW5nIHB1cnBvc2VzLiBJdCBjb250YWlucyBlbm91Z2ggZGF0YSB0byBzaW11bGF0ZSBhIGxhcmdlIHBheWxvYWQsIHN1Y2ggYXMgYW4gaW1hZ2UsIGEgZmlsZSwgb3IgYSBsZW5ndGh5IEpXVCB0b2tlbi4gTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZWxpdCwgc2VkIGRvIGVpdXNtb2QgdGVtcG9yIGluY2lkaWR1bnQgdXQgbGFib3JlIGV0IGRvbG9yZSBtYWduYSBhbGlxdWEuIFV0IGVuaW0gYWQgbWluaW0gdmVuaWFtLCBxdWlzIG5vc3RydWQgZXhlcmNpdGF0aW9uIHVsbGFtY28gbGFib3JpcyBuaXNpIHV0IGFsaXF1aXAgZXggZWEgY29tbW9kbyBjb25zZXF1YXQu